module.exports = {
  experts: [
    { id: 1, name: 'د. أحمد الخالدي', title: 'مهندس برمجيات أول', country: 'ألمانيا', city: 'برلين', field: 'تكنولوجيا المعلومات', exp: 12, skills: ['React', 'Node.js', 'Cloud Architecture', 'AI'], languages: ['العربية', 'الإنجليزية', 'الألمانية'], avatar: '👨‍💻', bio: 'مهندس برمجيات متخصص في بناء الأنظمة السحابية والذكاء الاصطناعي. عملت في Google و SAP.', available: true },
    { id: 2, name: 'د. سارة العبدالله', title: 'جراحة قلب', country: 'الولايات المتحدة', city: 'نيويورك', field: 'الصحة والطب', exp: 15, skills: ['جراحة القلب', 'زراعة الأعضاء', 'البحث الطبي'], languages: ['العربية', 'الإنجليزية'], avatar: '👩‍⚕️', bio: 'جراحة قلب في مستشفى Mount Sinai. خبرة 15 سنة في جراحة القلب المفتوح والتدخل المحدود.', available: true },
    { id: 3, name: 'محمد الرفاعي', title: 'مدير مشاريع إنشائية', country: 'تركيا', city: 'إسطنبول', field: 'الهندسة', exp: 10, skills: ['إدارة المشاريع', 'BIM', 'إعادة الإعمار', 'PMP'], languages: ['العربية', 'التركية', 'الإنجليزية'], avatar: '👷‍♂️', bio: 'أشرفت على مشاريع إعادة إعمار بقيمة 200 مليون دولار في تركيا والمنطقة.', available: true },
    { id: 4, name: 'د. لينا حداد', title: 'باحثة في الذكاء الاصطناعي', country: 'كندا', city: 'تورنتو', field: 'تكنولوجيا المعلومات', exp: 8, skills: ['Machine Learning', 'NLP', 'Python', 'Research'], languages: ['العربية', 'الإنجليزية', 'الفرنسية'], avatar: '👩‍🔬', bio: 'باحثة في معهد Vector Institute. متخصصة في معالجة اللغات الطبيعية والتعلم العميق.', available: true },
    { id: 5, name: 'عمر السيد', title: 'محاسب قانوني معتمد', country: 'المملكة المتحدة', city: 'لندن', field: 'المحاسبة والمالية', exp: 14, skills: ['CPA', 'IFRS', 'Audit', 'Tax Planning'], languages: ['العربية', 'الإنجليزية'], avatar: '👨‍💼', bio: 'محاسب قانوني معتمد في Deloitte London. خبرة في الضرائب الدولية والتدقيق.', available: false },
    { id: 6, name: 'د. ندى إبراهيم', title: 'أستاذة جامعية — هندسة مدنية', country: 'السويد', city: 'ستوكهولم', field: 'الهندسة', exp: 11, skills: ['Structural Engineering', 'Seismic Design', 'Sustainability'], languages: ['العربية', 'الإنجليزية', 'السويدية'], avatar: '👩‍🏫', bio: 'أستاذة مساعدة في KTH Royal Institute. متخصصة في الهندسة الزلزالية والبناء المستدام.', available: true },
    { id: 7, name: 'يوسف القاسم', title: 'مصمم منتجات UX/UI', country: 'هولندا', city: 'أمستردام', field: 'التسويق والمبيعات', exp: 7, skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping'], languages: ['العربية', 'الإنجليزية', 'الهولندية'], avatar: '🎨', bio: 'قاد فريق التصميم في Booking.com. متخصص في تصميم أنظمة التصميم وتجربة المستخدم.', available: true },
    { id: 8, name: 'د. رنا محفوض', title: 'اختصاصية تغذية سريرية', country: 'الإمارات', city: 'دبي', field: 'الصحة والطب', exp: 9, skills: ['Clinical Nutrition', 'Diabetes Care', 'Pediatrics'], languages: ['العربية', 'الإنجليزية'], avatar: '🥗', bio: 'اختصاصية تغذية في مستشفى أمريكي دبي. خبرة في التغذية السريرية وأمراض السكري.', available: true },
    { id: 9, name: 'خالد العمر', title: 'مدير سلاسل الإمداد', country: 'قطر', city: 'الدوحة', field: 'اللوجستيات والنقل', exp: 13, skills: ['Supply Chain', 'Logistics', 'Procurement', 'ERP'], languages: ['العربية', 'الإنجليزية'], avatar: '📦', bio: 'أدار سلاسل إمداد لشركات نفطية كبرى في الخليج. خبرة في التوريد واللوجستيات الدولية.', available: true },
    { id: 10, name: 'د. هبة الشامي', title: 'باحثة في الطاقة المتجددة', country: 'فرنسا', city: 'باريس', field: 'الهندسة', exp: 10, skills: ['Solar Energy', 'Grid Integration', 'Energy Policy'], languages: ['العربية', 'الإنجليزية', 'الفرنسية'], avatar: '⚡', bio: 'باحثة في CEA France. متخصصة في الطاقة الشمسية ودمج الشبكات الكهربائية.', available: true },
    { id: 11, name: 'عبدالله الناصر', title: 'مطور ألعاب فيديو', country: 'اليابان', city: 'طوكيو', field: 'تكنولوجيا المعلومات', exp: 6, skills: ['Unity', 'Unreal Engine', 'C++', 'Game Design'], languages: ['العربية', 'الإنجليزية', 'اليابانية'], avatar: '🎮', bio: 'عمل في Capcom و Square Enix. متخصص في تطوير ألعاب AAA.', available: true },
    { id: 12, name: 'د. فاطمة الزعبي', title: 'أخصائية نفسية سريرية', country: 'الأردن', city: 'عمان', field: 'الصحة والطب', exp: 16, skills: ['CBT', 'Trauma Therapy', 'Family Therapy', 'Supervision'], languages: ['العربية', 'الإنجليزية'], avatar: '🧠', bio: 'أخصائية نفسية مرخصة. خبرة في العلاج المعرفي السلوكي وعلاج الصدمات.', available: true }
  ],
  projects: [
    { id: 1, title: 'تصميم نظام إدارة مستشفيات', desc: 'نحتاج خبيراً في تطوير أنظمة HIS (Hospital Information System) لمدة 6 أشهر عن بُعد.', field: 'تكنولوجيا المعلومات', budget: '5000 - 8000 دولار', duration: '6 أشهر', type: 'عن بُعد', status: 'open', posted: '2026-07-10' },
    { id: 2, title: 'استشارات في إعادة تأهيل شبكات المياه', desc: 'مشروع استشاري لإعادة تأهيل شبكات المياه في ريف دمشق. يتطلب زيارات ميدانية دورية.', field: 'الهندسة', budget: '12000 - 18000 دولار', duration: '12 شهر', type: 'زيارات دورية', status: 'open', posted: '2026-07-08' },
    { id: 3, title: 'تدريب معلمين على مناهج STEM', desc: 'برنامج تدريبي لـ 50 معلماً على مناهج STEM للمرحلة الثانوية عن بُعد.', field: 'التعليم', budget: '3000 - 5000 دولار', duration: '3 أشهر', type: 'عن بُعد', status: 'open', posted: '2026-07-05' },
    { id: 4, title: 'تطوير استراتيجية تسويق رقمي للسياحة', desc: 'وضع استراتيجية تسويق رقمي شاملة لتنشيط السياحة في سوريا.', field: 'التسويق والمبيعات', budget: '4000 - 7000 دولار', duration: '4 أشهر', type: 'عن بُعد', status: 'open', posted: '2026-07-03' },
    { id: 5, title: 'تصميم منهج تدريبي في المحاسبة الدولية', desc: 'إعداد منهج تدريبي متكامل في المعايير المحاسبية الدولية IFRS.', field: 'المحاسبة والمالية', budget: '2500 - 4000 دولار', duration: '2 شهر', type: 'عن بُعد', status: 'open', posted: '2026-07-01' },
    { id: 6, title: 'إشراف على مشروع بناء مدرسة', desc: 'إشراف هندسي كامل على بناء مدرسة ابتدائية في ريف حلب.', field: 'الهندسة', budget: '8000 - 12000 دولار', duration: '18 شهر', type: 'ميداني', status: 'in-progress', posted: '2026-06-20' }
  ],
  mentors: [
    { id: 1, name: 'د. أحمد الخالدي', field: 'تكنولوجيا المعلومات', exp: '12 سنة', country: 'ألمانيا', rate: 'مجاناً', sessions: 45, avatar: '👨‍💻', topics: ['برمجة', 'تطوير الويب', 'السحابة'] },
    { id: 2, name: 'د. سارة العبدالله', field: 'الطب', exp: '15 سنة', country: 'الولايات المتحدة', rate: 'مجاناً', sessions: 32, avatar: '👩‍⚕️', topics: ['الطب', 'البحث العلمي', 'المنح'] },
    { id: 3, name: 'محمد الرفاعي', field: 'الهندسة المدنية', exp: '10 سنوات', country: 'تركيا', rate: 'مجاناً', sessions: 28, avatar: '👷‍♂️', topics: ['إدارة المشاريع', 'إعادة الإعمار', 'PMP'] },
    { id: 4, name: 'د. لينا حداد', field: 'الذكاء الاصطناعي', exp: '8 سنوات', country: 'كندا', rate: 'مجاناً', sessions: 56, avatar: '👩‍🔬', topics: ['Machine Learning', 'Python', 'البحث'] },
    { id: 5, name: 'يوسف القاسم', field: 'تصميم UX/UI', exp: '7 سنوات', country: 'هولندا', rate: 'مجاناً', sessions: 41, avatar: '🎨', topics: ['Figma', 'تجربة المستخدم', 'تصميم المنتجات'] },
    { id: 6, name: 'د. ندى إبراهيم', field: 'الهندسة المدنية', exp: '11 سنة', country: 'السويد', rate: 'مجاناً', sessions: 23, avatar: '👩‍🏫', topics: ['الهندسة الزلزالية', 'البناء المستدام', 'الأكاديميا'] }
  ],
  knowledge: [
    { id: 1, title: 'دليل إعادة إعمار البنية التحتية في المناطق المتضررة', desc: 'دليل شامل يتناول أفضل الممارسات في إعادة إعمار الطرق، الجسور، وشبكات المياه بعد النزاعات.', author: 'محمد الرفاعي', field: 'الهندسة', date: '2026-07-10', icon: '🏗️' },
    { id: 2, title: 'مقدمة في الذكاء الاصطناعي للمبتدئين', desc: 'سلسلة من 10 دروس تشرح أساسيات الذكاء الاصطناعي والتعلم الآلي بالعربية.', author: 'د. لينا حداد', field: 'تكنولوجيا المعلومات', date: '2026-07-08', icon: '🤖' },
    { id: 3, title: 'التغذية السليمة في ظروف الطوارئ', desc: 'إرشادات عملية للتغذية السليمة في المخيمات والمناطق المتضررة.', author: 'د. رنا محفوض', field: 'الصحة والطب', date: '2026-07-05', icon: '🥗' },
    { id: 4, title: 'كيف تبني مسيرة مهنية ناجحة في التكنولوجيا', desc: 'نصائح عملية من خبرة 12 سنة في شركات عالمية.', author: 'د. أحمد الخالدي', field: 'تكنولوجيا المعلومات', date: '2026-07-03', icon: '💼' },
    { id: 5, title: 'أساسيات المحاسبة الدولية IFRS', desc: 'شرح مبسط للمعايير المحاسبية الدولية مع أمثلة عملية.', author: 'عمر السيد', field: 'المحاسبة والمالية', date: '2026-07-01', icon: '📊' },
    { id: 6, title: 'الطاقة الشمسية في سوريا: الفرص والتحديات', desc: 'دراسة تحليلية لإمكانات الطاقة الشمسية في سوريا وكيفية الاستثمار فيها.', author: 'د. هبة الشامي', field: 'الهندسة', date: '2026-06-28', icon: '☀️' }
  ],
  courses: [
    { id: 1, title: 'مقدمة في تطوير الويب Full-Stack', instructor: 'د. أحمد الخالدي', country: 'ألمانيا', field: 'تكنولوجيا المعلومات', duration: '6 أسابيع', level: 'مبتدئ', students: 320, format: 'عن بُعد', icon: '💻' },
    { id: 2, title: 'أساسيات إدارة المشاريع الهندسية PMP', instructor: 'محمد الرفاعي', country: 'تركيا', field: 'الهندسة', duration: '4 أسابيع', level: 'متوسط', students: 210, format: 'عن بُعد', icon: '📐' },
    { id: 3, title: 'الإسعافات الأولية والرعاية الصحية الطارئة', instructor: 'د. سارة العبدالله', country: 'الولايات المتحدة', field: 'الصحة والطب', duration: '3 أسابيع', level: 'مبتدئ', students: 450, format: 'عن بُعد', icon: '🩺' },
    { id: 4, title: 'تعلّم الآلة والذكاء الاصطناعي من الصفر', instructor: 'د. لينا حداد', country: 'كندا', field: 'تكنولوجيا المعلومات', duration: '8 أسابيع', level: 'متقدم', students: 180, format: 'عن بُعد', icon: '🤖' },
    { id: 5, title: 'تصميم تجربة وواجهة المستخدم UX/UI', instructor: 'يوسف القاسم', country: 'هولندا', field: 'التصميم', duration: '5 أسابيع', level: 'مبتدئ', students: 265, format: 'عن بُعد', icon: '🎨' },
    { id: 6, title: 'المحاسبة المالية للمشاريع الصغيرة', instructor: 'عمر السيد', country: 'قطر', field: 'المحاسبة والمالية', duration: '4 أسابيع', level: 'مبتدئ', students: 190, format: 'عن بُعد', icon: '📊' },
    { id: 7, title: 'أساسيات التدريس الفعّال في مرحلة الطوارئ التعليمية', instructor: 'د. ندى إبراهيم', country: 'السويد', field: 'التعليم', duration: '3 أسابيع', level: 'مبتدئ', students: 300, format: 'عن بُعد', icon: '📚' },
    { id: 8, title: 'ريادة الأعمال وبناء المشاريع الناشئة', instructor: 'د. هبة الشامي', country: 'الإمارات', field: 'ريادة الأعمال', duration: '6 أسابيع', level: 'متوسط', students: 275, format: 'عن بُعد', icon: '🚀' }
  ]
};
